### ISSUE TITLE
stored defaults

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/ask-once#1]
Just curious, how does [this work](https://github.com/doowb/ask-once/blob/master/index.js#L70-L71)? is the goal to only updated the in-memory "default"? or should it store that default (when `force` is defined)?  I'm not sure. 

Also, since `q` only exists in that if statement, how is this actually storing the value? by reference (to the question object that's returned)?

``` js
var q = questions.get(question);
q.default = answer;
```

edit: and if so, it doesn't look like that would store the answer on subsequent runs, only in-memory. again just curious

**Comment by doowb** [comment]
It updates the reference that's stored in question cache, then is used when asking the question. It gets saved back to the store when the user answers the question. I thought about doing some logic to only set the default if it was already undefined but this seems to be a good workflow.

Try out the example using `-i` and `-f` in different orders. Maybe I should run it a few times and take screenshoots to show the different cases since it's hard to do tests for these.

**Comment by jonschlinkert** [comment]
k, I'll take another look today, thanks for explaining

**Comment by jonschlinkert** [comment]
I might be missing something, but won't [this line](https://github.com/doowb/ask-once/blob/master/index.js#L71) be useless if [the value is undefined](https://github.com/doowb/ask-once/blob/master/index.js#L66)?

**Comment by doowb** [comment]
Yeah, but there's an `or` clause in that `if`, so that's only really useful if the value was already stored and the `force` option is `true`. It's just saying that when forcing to ask the question again, use the previously stored value as the default for the question instead of the specified default.

**Comment by doowb** [comment]
Code has changed since this issue was open. Closing.
